-- UK Frontier Technology Policy Tracker — initial schema migration.
--
-- This is Prisma's baseline migration, generated by hand-copying
-- docs/schema.sql (the design reference — see that file for the rationale
-- behind each table). Keep the two in sync: change the schema by editing
-- prisma/schema.prisma and running `prisma migrate dev`, then mirror the
-- result back into docs/schema.sql for anyone reading the design docs
-- without a Postgres client handy.
--
-- Target: plain Postgres (Neon). No Supabase-specific features used.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE section_key AS ENUM (
  'timeline', 'institution', 'initiative', 'regulation', 'breakthrough', 'evolving'
);

CREATE TYPE subtab_key AS ENUM (
  'domestic', 'international',
  'export', 'nsi', 'standards', 'ipsec',
  'crit-infra', 'cybercrime', 'consumer-telecoms', 'codes-standards',
  'spectrum', 'infra-access', 'satellite'
);

CREATE TYPE record_status  AS ENUM ('active', 'dissolved', 'paused', 'liquidation');
CREATE TYPE source_tier    AS ENUM ('primary', 'secondary', 'partial');
CREATE TYPE date_precision AS ENUM ('year', 'month', 'day', 'range');

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ═══════════════════════════════════════════════════════════════
-- v2 base — sectors, records, badges, record_badges, record_history
-- ═══════════════════════════════════════════════════════════════

-- ─────────────────────────── sectors ───────────────────────────
CREATE TABLE sectors (
  sector_id           text PRIMARY KEY,
  label               text NOT NULL,
  status              text NOT NULL DEFAULT 'active' CHECK (status IN ('active','placeholder')),
  framing_text        text,
  methodology_notes   text,
  last_reviewed_date  date,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_sectors_updated_at
  BEFORE UPDATE ON sectors
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────── records ───────────────────────────
CREATE TABLE records (
  record_id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  record_key           text NOT NULL UNIQUE,
  sector_id            text NOT NULL REFERENCES sectors(sector_id),
  section_key          section_key NOT NULL,
  subtab_key           subtab_key,
  title                text NOT NULL,
  subtitle             text,
  date_label           text,
  date_sort_key        date,
  date_precision       date_precision,
  description          text NOT NULL,
  url                  text,
  url_verified         boolean NOT NULL DEFAULT false,
  caveat               text,
  status               record_status NOT NULL DEFAULT 'active',
  is_placeholder       boolean NOT NULL DEFAULT false,
  canonical_record_id  uuid REFERENCES records(record_id),
  source_tier          source_tier,
  last_verified_date   date,
  sort_order           int,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT subtab_only_for_initiative_or_regulation CHECK (
    subtab_key IS NULL OR section_key IN ('initiative', 'regulation')
  ),
  CONSTRAINT placeholder_requires_canonical CHECK (
    is_placeholder = false OR canonical_record_id IS NOT NULL
  )
);

CREATE INDEX idx_records_sector_section  ON records(sector_id, section_key);
CREATE INDEX idx_records_subtab          ON records(subtab_key) WHERE subtab_key IS NOT NULL;
CREATE INDEX idx_records_canonical       ON records(canonical_record_id) WHERE canonical_record_id IS NOT NULL;
CREATE INDEX idx_records_last_verified   ON records(last_verified_date);

CREATE TRIGGER trg_records_updated_at
  BEFORE UPDATE ON records
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────── badges ───────────────────────────
CREATE TABLE badges (
  badge_id   text PRIMARY KEY,
  sector_id  text NOT NULL REFERENCES sectors(sector_id),
  label      text NOT NULL,
  UNIQUE (sector_id, label)
);

CREATE TABLE record_badges (
  record_id  uuid NOT NULL REFERENCES records(record_id) ON DELETE CASCADE,
  badge_id   text NOT NULL REFERENCES badges(badge_id),
  PRIMARY KEY (record_id, badge_id)
);

-- ─────────────────────────── record_history ───────────────────────────
CREATE TABLE record_history (
  history_id     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  record_id      uuid NOT NULL REFERENCES records(record_id),
  changed_field  text NOT NULL,
  old_value      text,
  new_value      text,
  change_reason  text,
  source_ref     text,
  changed_by     text NOT NULL,
  changed_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_record_history_record ON record_history(record_id, changed_at);

-- ═══════════════════════════════════════════════════════════════
-- Extensions — proposed in docs/DESIGN.md, not part of v2
-- ═══════════════════════════════════════════════════════════════

-- ─────────────────────────── people (named leaders) ───────────────────────────
-- Ministers, agency heads, named researchers — the linkage point the briefing
-- notes describe against the investor tracker's PSC/GP identities. Populated
-- deliberately during authoring, not mined from free-text description/subtitle.
CREATE TABLE people (
  person_id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name        text NOT NULL,
  normalized_name  text NOT NULL,   -- lowercased, punctuation-stripped; future PSC/GP matching key
  role_title       text,            -- current/most-recent role, free text
  notes            text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_people_normalized_name ON people(normalized_name);

CREATE TRIGGER trg_people_updated_at
  BEFORE UPDATE ON people
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE record_people (
  record_id     uuid NOT NULL REFERENCES records(record_id) ON DELETE CASCADE,
  person_id     uuid NOT NULL REFERENCES people(person_id),
  role_at_time  text,   -- role as it applied to this specific record, e.g. "Chancellor" at time of entry
  PRIMARY KEY (record_id, person_id)
);

-- ─────────────────────────── sector_taxonomy_xref (alignment guard) ───────────────────────────
-- Not a new taxonomy. Records which external ontology code (e.g. QUILT's Deep
-- Tech Ontology top-level category) each sector corresponds to, so drift
-- between systems is one mapping row, not a record_key rename cascade.
-- Left unpopulated until QUILT's category codes are confirmed.
CREATE TABLE sector_taxonomy_xref (
  sector_id        text NOT NULL REFERENCES sectors(sector_id),
  external_system  text NOT NULL,   -- e.g. 'quilt_deep_tech_ontology'
  external_code    text NOT NULL,
  PRIMARY KEY (sector_id, external_system)
);

-- ─────────────────────────── v_policy_signal_by_category ───────────────────────────
-- Narrow, stable read surface for the connecting repository / QUILT-side
-- tooling: category + month + record identity, nothing internal. This is the
-- concrete surface behind the "two-clock mismatch, made measurable" claim —
-- the funding-vs-policy comparison itself happens outside this repo.
CREATE VIEW v_policy_signal_by_category AS
SELECT
  r.sector_id,
  s.label                                     AS sector_label,
  r.section_key,
  date_trunc('month', r.date_sort_key)::date  AS signal_month,
  r.record_key,
  r.title,
  r.status,
  r.source_tier
FROM records r
JOIN sectors s USING (sector_id)
WHERE r.date_sort_key IS NOT NULL
  AND r.is_placeholder = false;
