// Transforms the extracted prototype data (scripts/migrate/.extract.json,
// produced by extract.mjs) into db/seed/001_migrated_records.sql — plain SQL
// INSERT statements against the schema in docs/schema.sql, following the
// crosswalk rules in docs/DESIGN.md and the v2 schema doc:
//
//   - `type` migrates to subtab_key ONLY for initiative/regulation rows;
//     dropped everywhere else (breakthrough categorisation lives in badges).
//   - badges migrate ONLY for breakthrough rows; regulation-row badges and
//     the dissolved/paused/unresolved badges duplicate other fields and are
//     dropped (derivable from subtab_key/section_key/status at query time).
//   - record_key = {sector}__{section}__{title-slug}, generated once here.
//   - Every migrated row gets one record_history entry.
//   - last_verified_date defaults to the sector's last_reviewed_date, since
//     v1 tracked verification per-sector ("researched August 2026" in the
//     footer prose) rather than per-record.
//   - sort_order preserves each record's original index within its
//     (sector, section) — the prototype has no sort logic at all, display
//     order is array order, so this is lossless insurance for the app layer.
//
// Usage: node scripts/migrate/extract.mjs > scripts/migrate/.extract.json
//        node scripts/migrate/build-seed.mjs

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import crypto from 'node:crypto';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const extractPath = path.join(__dirname, '.extract.json');
const outPath = path.join(__dirname, '../../db/seed/001_migrated_records.sql');

const data = JSON.parse(readFileSync(extractPath, 'utf8'));

const MONTHS = { Jan:1,Feb:2,Mar:3,Apr:4,May:5,Jun:6,Jul:7,Aug:8,Sep:9,Oct:10,Nov:11,Dec:12 };
const INITIATIVE_REGULATION_TYPES = new Set([
  'domestic','international',
  'export','nsi','standards','ipsec',
  'crit-infra','cybercrime','consumer-telecoms','codes-standards',
  'spectrum','infra-access','satellite'
]);

function sqlStr(v) {
  if (v === null || v === undefined) return 'NULL';
  return "'" + String(v).replace(/'/g, "''") + "'";
}
function sqlBool(v) { return v ? 'true' : 'false'; }
function sqlDate(v) { return v === null ? 'NULL' : `'${v}'`; }
function sqlInt(v) { return v === null || v === undefined ? 'NULL' : String(v); }
function stripTags(s) { return (s || '').replace(/<\/?[a-z]+>/gi, ''); }
function slug(s) {
  return String(s || '')
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}
function orNull(s) { return s === '' || s === undefined ? null : s; }

// Best-effort date parse. Returns { sort, precision } — both null if
// unparseable, matching v2's rationale for keeping date_label verbatim
// alongside a nullable date_sort_key.
function parseDate(label) {
  const t = (label || '').trim();
  if (!t) return { sort: null, precision: null };

  let m = t.match(/^(\d{1,2})\s+([A-Za-z]{3})\s+(\d{4})$/);
  if (m && MONTHS[m[2]]) {
    return { sort: `${m[3]}-${String(MONTHS[m[2]]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`, precision: 'day' };
  }
  m = t.match(/^([A-Za-z]{3})\s+(\d{4})$/);
  if (m && MONTHS[m[1]]) {
    return { sort: `${m[2]}-${String(MONTHS[m[1]]).padStart(2,'0')}-01`, precision: 'month' };
  }
  if (/^\d{4}$/.test(t)) {
    return { sort: `${t}-01-01`, precision: 'year' };
  }
  // Qualified / range-ish strings ("Since Dec 2025", "Jul 2026 – ongoing", "c. 2020")
  m = t.match(/(\d{1,2})\s+([A-Za-z]{3})\s+(\d{4})/);
  if (m && MONTHS[m[2]]) {
    return { sort: `${m[3]}-${String(MONTHS[m[2]]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`, precision: 'range' };
  }
  m = t.match(/([A-Za-z]{3})\s+(\d{4})/);
  if (m && MONTHS[m[1]]) {
    return { sort: `${m[2]}-${String(MONTHS[m[1]]).padStart(2,'0')}-01`, precision: 'range' };
  }
  m = t.match(/(\d{4})/);
  if (m) return { sort: `${m[1]}-01-01`, precision: 'range' };

  return { sort: null, precision: null };
}
function monthLabelToISODate(label) {
  // "July 2026" -> "2026-07-01", for sectors.last_reviewed_date
  const m = (label || '').match(/([A-Za-z]+)\s+(\d{4})/);
  if (!m) return null;
  const monthIdx = Object.keys(MONTHS).findIndex(k => m[1].startsWith(k));
  if (monthIdx === -1) return null;
  const monthNum = Object.values(MONTHS)[monthIdx];
  return `${m[2]}-${String(monthNum).padStart(2,'0')}-01`;
}

const lines = [];
lines.push('-- Auto-generated by scripts/migrate/build-seed.mjs — do not hand-edit.');
lines.push('-- Regenerate: node scripts/migrate/extract.mjs > scripts/migrate/.extract.json && node scripts/migrate/build-seed.mjs');
lines.push('BEGIN;');
lines.push('');

// ── sectors ──
lines.push('-- ═══ sectors ═══');
for (const meta of data.SECTOR_META) {
  const lastReviewed = monthLabelToISODate(meta.updated);
  lines.push(
    `INSERT INTO sectors (sector_id, label, status, framing_text, methodology_notes, last_reviewed_date) VALUES (` +
    `${sqlStr(meta.key)}, ${sqlStr(meta.label)}, ${sqlStr(meta.status)}, ` +
    `${sqlStr(orNull(data.SECTOR_FRAMING[meta.key]))}, ${sqlStr(stripTags(data.SECTOR_FOOTER[meta.key]))}, ${sqlDate(lastReviewed)}` +
    `) ON CONFLICT (sector_id) DO NOTHING;`
  );
}
// Placeholder sector — exercises the is_placeholder/"Coming soon" pattern
// ahead of a confirmed seventh frontier technology (see docs/DESIGN.md,
// Resolved decisions #3). Rename/replace sector_id and label once known.
lines.push(
  `INSERT INTO sectors (sector_id, label, status, framing_text, methodology_notes, last_reviewed_date) VALUES (` +
  `'tbd-seventh', 'TBD — seventh frontier technology', 'placeholder', NULL, ` +
  `${sqlStr('Placeholder sector exercising the placeholder-sector pattern ahead of a confirmed seventh frontier technology category. Replace sector_id, label, and status once named.')}, NULL` +
  `) ON CONFLICT (sector_id) DO NOTHING;`
);
lines.push('');

// ── badges (breakthrough-row labels only) ──
lines.push('-- ═══ badges (breakthrough-row labels only, per v2 crosswalk) ═══');
const badgeIdBySectorLabel = new Map(); // "sector||label" -> badge_id
for (const [sectorKey, records] of Object.entries(data.SECTOR_DATA)) {
  const seen = new Set();
  for (const r of records) {
    if (r.section !== 'breakthrough') continue;
    for (const label of r.badges) {
      const key = `${sectorKey}||${label}`;
      if (seen.has(key)) continue;
      seen.add(key);
      const badgeId = `${sectorKey}__${slug(label)}`;
      badgeIdBySectorLabel.set(key, badgeId);
      lines.push(
        `INSERT INTO badges (badge_id, sector_id, label) VALUES (${sqlStr(badgeId)}, ${sqlStr(sectorKey)}, ${sqlStr(label)}) ` +
        `ON CONFLICT (sector_id, label) DO NOTHING;`
      );
    }
  }
}
lines.push('');

// ── records, record_badges, record_history ──
lines.push('-- ═══ records ═══');
const recordBadgeLines = [];
const recordHistoryLines = [];
const recordKeyCounts = new Map();
let totalRecords = 0;

for (const meta of data.SECTOR_META) {
  const sectorKey = meta.key;
  const lastVerified = monthLabelToISODate(meta.updated);
  const records = data.SECTOR_DATA[sectorKey];
  const sortOrderBySection = new Map();

  for (const r of records) {
    totalRecords++;
    const sortOrder = sortOrderBySection.get(r.section) ?? 0;
    sortOrderBySection.set(r.section, sortOrder + 1);

    const isInitOrReg = r.section === 'initiative' || r.section === 'regulation';
    const subtabKey = isInitOrReg && INITIATIVE_REGULATION_TYPES.has(r.type) ? r.type : null;

    let recordKey = `${sectorKey}__${r.section}__${slug(r.title)}`;
    const dupCount = recordKeyCounts.get(recordKey) || 0;
    recordKeyCounts.set(recordKey, dupCount + 1);
    if (dupCount > 0) recordKey = `${recordKey}-${dupCount + 1}`;

    const { sort: dateSortKey, precision: datePrecision } = parseDate(r.date);
    const recordId = crypto.randomUUID();

    lines.push(
      `INSERT INTO records (record_id, record_key, sector_id, section_key, subtab_key, title, subtitle, date_label, date_sort_key, date_precision, description, url, url_verified, caveat, status, last_verified_date, sort_order) VALUES (` +
      `${sqlStr(recordId)}, ${sqlStr(recordKey)}, ${sqlStr(sectorKey)}, ${sqlStr(r.section)}, ${subtabKey ? sqlStr(subtabKey) : 'NULL'}, ` +
      `${sqlStr(r.title)}, ${sqlStr(orNull(r.subtitle))}, ${sqlStr(orNull(r.date))}, ${sqlDate(dateSortKey)}, ${datePrecision ? sqlStr(datePrecision) : 'NULL'}, ` +
      `${sqlStr(r.description)}, ${sqlStr(orNull(r.url))}, ${sqlBool(r.url_verified === 'yes')}, ${sqlStr(orNull(r.caveat))}, ${sqlStr(r.status || 'active')}, ` +
      `${sqlDate(lastVerified)}, ${sqlInt(sortOrder)}` +
      `) ON CONFLICT (record_key) DO NOTHING;`
    );

    if (r.section === 'breakthrough') {
      for (const label of r.badges) {
        const badgeId = badgeIdBySectorLabel.get(`${sectorKey}||${label}`);
        recordBadgeLines.push(
          `INSERT INTO record_badges (record_id, badge_id) VALUES (${sqlStr(recordId)}, ${sqlStr(badgeId)}) ON CONFLICT DO NOTHING;`
        );
      }
    }

    recordHistoryLines.push(
      `INSERT INTO record_history (record_id, changed_field, old_value, new_value, change_reason, changed_by) VALUES (` +
      `${sqlStr(recordId)}, 'record', NULL, ${sqlStr(r.title)}, 'migrated from HTML prototype', 'migration-script');`
    );
  }
}
lines.push('');
lines.push('-- ═══ record_badges ═══');
lines.push(...recordBadgeLines);
lines.push('');
lines.push('-- ═══ record_history ═══');
lines.push(...recordHistoryLines);
lines.push('');
lines.push('COMMIT;');

mkdirSync(path.dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join('\n') + '\n');

console.log(`Wrote ${outPath}`);
console.log(`  sectors: ${data.SECTOR_META.length} + 1 placeholder`);
console.log(`  badges: ${badgeIdBySectorLabel.size}`);
console.log(`  records: ${totalRecords}`);
console.log(`  record_badges: ${recordBadgeLines.length}`);
console.log(`  record_history: ${recordHistoryLines.length}`);
